name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven auth (GitHub Packages)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show current version (sanity)
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: Build and deploy security-common to GitHub Packages
        run: mvn -B -DskipTests clean deploy