name: Publish to GitHub Packages

on:
  push:
    tags: [ 'v*.*.*' ]
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK and Maven auth (GitHub Packages)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: Build and deploy
        run: mvn -B -DskipTests clean deploy
